---
triple:          'arm64-apple-darwin'
binary-path:     build
relocations:
  - { offset: 0x26, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003F04, symSize: 0x74 }
  - { offset: 0x41, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003F04, symSize: 0x74 }
...
